# Generated by Django 5.2.5 on 2025-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_pendingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingquestion',
            name='test_cases_data',
            field=models.JSONField(blank=True, help_text='Test cases submitted with the question', null=True),
        ),
    ]
