# Generated by Django 5.2.5 on 2025-08-16 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0003_submission_test_case_results_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(help_text='Detailed feedback from AI code analysis')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall score from 0 to 100', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='problems.submission')),
            ],
            options={
                'verbose_name': 'AI Review Result',
                'verbose_name_plural': 'AI Review Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('total_submissions', models.IntegerField()),
                ('accepted_submissions', models.IntegerField()),
                ('accuracy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category_breakdown', models.JSONField(blank=True, help_text='JSON field for category-wise statistics', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Snapshot',
                'verbose_name_plural': 'Progress Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
